version: '3.8'

services:
  daily-update:
    image: data-daily-update:latest
    build:
      context: .
      dockerfile: Dockerfile.daily_update
    container_name: data-daily-update
    volumes:
      - ./logs:/app/logs
      - ../data:/app/data
    environment:
      - TZ=Asia/Shanghai
    restart: unless-stopped
    command: >
      sh -c "mkdir -p /app/logs && touch /app/logs/cron.log && cron && tail -f /app/logs/cron.log" 